name: Update Counter

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increase counter
        run: |
          count=$(jq '.visits' counter.json)
          newcount=$((count + 1))
          echo "{ \"visits\": $newcount }" > counter.json

      - name: Commit changes
        run: |
          git config --global user.name "counter-bot"
          git config --global user.email "counter@github.com"
          git add counter.json
          git commit -m "Update counter"
          git push
