name: Update Counter

on:
  repository_dispatch:
    types: [increment-counter]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read counter
        id: read
        run: |
          count=$(grep -o '[0-9]\+' counter.json)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Increment counter
        run: |
          new_count=$(( ${{ steps.read.outputs.count }} + 1 ))
          echo "{ \"visits\": $new_count }" > counter.json

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
        run: |
          git config user.name "AL3DPrint Bot"
          git config user.email "bot@al3dprint.de"
          git add counter.json
          git commit -m "Increment counter" || echo "No changes"
          git push https://AL3DPrint:${GITHUB_TOKEN}@github.com/AL3DPrint/al3dprint-counter.git
